name: Actualizar CSV diariamente

on:
  schedule:
    - cron: '0 8 * * *'  # Ejecuta el flujo de trabajo todos los días a las 8 am (UTC)
  workflow_dispatch:  # Permite la ejecución manual desde la interfaz de GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest  # El flujo de trabajo se ejecutará en un contenedor Ubuntu

    steps:
    - name: Hacer checkout del repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias del proyecto

    - name: Ejecutar script de Python
      run: |
        python main.py  # Ejecuta el script Python
