name: Automatización de carga de datos a Google Drive

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente
  schedule:
    - cron: "0 8 * * *"  # Ejecuta el workflow todos los días a las 08:00 UTC

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3  # Clona el repositorio

    - name: Crear archivo mycreds.txt desde el secreto
      run: |
        echo "${{ secrets.GDRIVE_CLIENT_SECRETS }}" > mycreds.txt  # Crea el archivo con las credenciales

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias listadas en requirements.txt

    - name: Ejecutar script
      run: python main.py  # Ejecuta el script Python

    - name: Subir el archivo a Google Drive
      run: |
        python main.py  # Vuelve a ejecutar el script para subir el archivo a Google Drive
