name: Actualizar CSV diario

on:
  schedule:
    - cron: '0 8 * * *'  # Ejecuta todos los días a las 08:00 UTC
  workflow_dispatch:     # Permite lanzarlo manualmente

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Instalar dependencias
        run: pip install pandas requests

      - name: Ejecutar script de actualización
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python main.py
